### ISSUE TITLE
Graph traversal (mostly) from disk, without loading entire graph in memory

### ISSUE THREAD

**Issue by yaacoo** [aprilweilab/grgl#27]
Do you have advice on how to use your data structure without loading the entire chromosome graph in memory? 

For example, querying variant-to-sample or sample-to-variant, while keeping most of the data on disk, and only necessary units of of the graph traversal in memory? Indexed compressed VCF/BCF allow loading only relevant lines in memory. 

Thank you!

**Comment by dcdehaas** [comment]
This isn't possible with the current APIs, but is definitely on our radar to implement. The on-disk representation of the down-edges is (mostly) identical to the in-RAM representation. The first version of this is likely to:
1. Support traversal of the full graph (via node-id ordering) in either direction
2. Support subset traversal of the graph in the downward direction

One of the reasons that VCF/BCF only load relevant lines into memory is that it would be prohibitive to do otherwise. For GRG, you can load biobank-scale whole genome sequences into RAM (using anywhere from ~3-26GB, depending on which edges you load and which chromosome), and then traversal is much faster.

Prior to implementing the on-disk access, we are likely to implement an encoding that will decrease RAM usage as well.

**Comment by yaacoo** [comment]
Thank you

**Comment by dcdehaas** [comment]
I created https://github.com/aprilweilab/grgl/issues/29 to track this functionality. Feel free to subscribe to notifications on that issue if you are interested in when we implement this feature!
